In [1]:
import numpy as np
import pandas as pd

data = pd.read_csv('...\\Predicting Pulsars\\pulsar_stars.csv')

Data yang digunakan untuk dianalisis disini adalah data yang berasal dari kaggle dengan link berikut https://www.kaggle.com/pavanraj159/predicting-a-pulsar-star. Data ini adalah data-data pengamatan pulsar, atau #neutron star yang berotasi dengan sangat cepat. Langkah pertama yang tentunya harus dilakukan adalah meng-import atau memasukkan data-data tersebut ke dalam kernel kita.

Setelah data-data tersebut sudah berhasil di masukkan ke dalam kernel, tentu kita juga perlu mengetahui bentuk dari data-data tersebut. Disini saya menggunakan fungsi #head yang bisa menunjukkan 10 data teratas beserta dengan masing-masing nama kolomnya.

In [2]:
data.head(10)

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0
5,93.570312,46.698114,0.531905,0.416721,1.636288,14.545074,10.621748,131.394004,0
6,119.484375,48.765059,0.031460,-0.112168,0.999164,9.279612,19.206230,479.756567,0
7,130.382812,39.844056,-0.158323,0.389540,1.220736,14.378941,13.539456,198.236457,0
8,107.250000,52.627078,0.452688,0.170347,2.331940,14.486853,9.001004,107.972506,0
9,107.257812,39.496488,0.465882,1.162877,4.079431,24.980418,7.397080,57.784738,0

Setelah dilihat bentuk data-data ini, bisa dilihat bahwa nama-nama kolomnya masih terlalu sulit dan panjang. Untuk memudahkan analisis nantinya, nama-nama tersebut dirasa perlu diganti dengan nama-nama yang lebih jelas dan lebih pendek.

In [50]:
data.columns = ['mean', 'standard_deviation', 'excess_kurtosis',
                'skewness', 'mean_DM', 'standard_deviation_DM',
                'excess_kurtosis_DM', 'skewness_DM', 'target']
data.head(5)

,mean,standard_deviation,excess_kurtosis,skewness,mean_DM,standard_deviation_DM,excess_kurtosis_DM,skewness_DM,target
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

Kemudian data-data tersebut perlu di ubah ke dalam skala 0 sampai 1. Hal ini dilakukan untuk memudahkan analisis menggunakan #machine learning nantinya

In [52]:
from sklearn.preprocessing import MinMaxScaler

In [54]:
data_2 = data

x = np.reshape(np.array(data['mean']), [-1, 1])
scaler = MinMaxScaler().fit(x)
data_2['mean'] = scaler.transform(x)

In [63]:
col = data.columns

for x in range(8):
    y = np.reshape(np.array(data[col[x]]), [-1, 1])
    scaler = MinMaxScaler().fit(y)
    data_2[col[x]] = scaler.transform(y)

In [64]:
data_2.head(5)

,mean,standard_deviation,excess_kurtosis,skewness,mean_DM,standard_deviation_DM,excess_kurtosis_DM,skewness_DM,target
0,0.721342,0.417687,0.165043,0.015627,0.013382,0.113681,0.294986,0.063890,0
1,0.517628,0.460908,0.235415,0.018268,0.006560,0.072524,0.364015,0.108443,0
2,0.520346,0.196868,0.221138,0.040677,0.013030,0.139188,0.288624,0.054610,0
3,0.700933,0.437884,0.181750,0.016534,0.015368,0.131583,0.266348,0.046581,0
4,0.443854,0.214847,0.249044,0.041712,0.004327,0.039684,0.462029,0.213369,0

Setelah itu, data-data tersebut perlu dibagi menjadi dua berdasarkan targetnya. Jika target menunjukkan angka 0 itu artinya objek yang diamati tersebut bukan #neutron star, sedangkan jika bernilai 1 maka objek tersebut adalah #neutron star.

In [65]:
stars = data_2[data_2['target'] == 1]
nonstars = data_2[data_2['target'] == 0]

In [71]:
stars_target = stars.target
nonstars_target = nonstars.target

stars = stars.drop(['target'], axis=1)
nonstars = nonstars.drop(['target'], axis=1)

Lalu, langkah berikutnya yang saya ambil adalah membagi data menjadi dua kelompok, kelompok train dan kelompok test. Data yang berada pada kelompok train adalah data yang akan digunakan untuk melatih sistem #machine learning sedangkan data pada kelompok test adalah data yang akan menguji sistem #machine learning tersebut.

In [72]:
from sklearn.model_selection import train_test_split

x1_train, x1_test, y1_train, y1_test = train_test_split(stars, stars_target, test_size=0.3)
x2_train, x2_test, y2_train, y2_test = train_test_split(nonstars, nonstars_target, test_size=0.3)

In [75]:
x_train = pd.concat([x1_train, x2_train])
x_test = pd.concat([x1_test, x2_test])
y_train = pd.concat([y1_train, y2_train])
y_test = pd.concat([y1_test, y2_test])

Kemudian, saya memasukkan semua #library machine learning yang saya butuhkan.

In [76]:
from sklearn.linear_model import LogisticRegression, SGDClassifier, LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, VotingClassifier
from sklearn.naive_bayes import GaussianNB

In [ ]:
Analisis pun dimulai.

In [81]:
test = [LogisticRegression(), KNeighborsClassifier(), SVC(kernel='linear', C=0.025), SGDClassifier(max_iter=1000),
        LinearRegression(),DecisionTreeClassifier(), RandomForestClassifier(), MLPClassifier(max_iter=1000),
        AdaBoostClassifier(), GaussianNB()]
score = np.zeros([len(test), 1])

In [82]:
for clf, x in zip(test, range(len(test))):
    classifier = clf.fit(x_train, y_train)
    score[x] = classifier.score(x_test, y_test)

In [83]:
score

array([[0.97299814],
       [0.97914339],
       [0.96163873],
       [0.97467412],
       [0.67606804],
       [0.97113594],
       [0.98063315],
       [0.97858473],
       [0.97858473],
       [0.94413408]])

In [89]:
names = ['Logistic Regression', 'KNN', 'SVM', 'SGD Classifier', 'Linear Regression',
         'Decision Tree', 'Random Forest', 'Neural Network', 'AdaBoost Classifier',
         'Naive Bayes']
names = pd.DataFrame(np.transpose(np.array(names)))

In [90]:
score = pd.DataFrame(score)
scores = pd.concat([names, score], axis=1)
scores.columns = ['Methods', 'Score']

In [91]:
scores

               Methods     Score
0  Logistic Regression  0.972998
1                  KNN  0.979143
2                  SVM  0.961639
3       SGD Classifier  0.974674
4    Linear Regression  0.676068
5        Decision Tree  0.971136
6        Random Forest  0.980633
7       Neural Network  0.978585
8  AdaBoost Classifier  0.978585
9          Naive Bayes  0.944134

Dari sini, didapatkan sebuah hasil dimana metode random forest adalah metode yang memiliki akurasi prediksi yang paling tinggi. Sedangkan regresi linear adalah metode dengan nilai akurasi yang paling rendah. tentu masing-masing metode memilki kekurangan dan kelebihannya masing-masing. Dalam kasus ini, linear regression menjadi satu-satunya metode yang memiliki akurasi di bawah 0.9, bahkan hanya senilai 0.67. Tapi, pasti dalam kasus-kasus #machine learning yang lain, metode linear regression bisa saja menjadi metode terbaik yang dapat digunakan.